[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true

optimizer = true
optimizer_runs = 1000000

fuzz = { runs = 1000 }

remappings = [
    "@openzeppelin/contracts/=lib/v4-periphery/lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "v4-core/=lib/v4-periphery/lib/v4-core/src/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "forge-std/=lib/forge-std/src/"
]